### ISSUE TITLE
Climate entities unavailable

### ISSUE THREAD

**Issue by marekbrezina** [djerik/wavinsentio-ha#6]
Hello, 
there is an issue with my climates - all entities are unavailable. 
The log shows an error see below. 
I am not using the entities too often so I am not sure if the issue is related to any specific HA version however I am keeping HA and all integrations up to date so I am rather surprised nobody else has reported the issue. 
I have tried to disable the integration and enable again (with HA restarted) but with no luck.  
Thanks for your help.
cheers Marek

```
Logger: homeassistant.components.climate
Source: custom_components/wavinsentio/climate.py:67
Integration: Klima (documentation, issues)
First occurred: 21:12:23 (1 occurrences)
Last logged: 21:12:23

Error while setting up wavinsentio platform for climate
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 249, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/wavinsentio/climate.py", line 67, in async_setup_entry
    api = await hass.async_add_executor_job(
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.9/site-packages/wavinsentio/wavinsentio.py", line 21, in __init__
    self.__login()
  File "/usr/local/lib/python3.9/site-packages/wavinsentio/wavinsentio.py", line 49, in __login
    raise ApiError('GET /tasks/ {}'.format(resp.status_code))
NameError: name 'ApiError' is not defined

```

**Comment by djerik** [comment]
The error message suggest, that there is a problem logging in. Maybe you have changed password? Please also check if the native Wavin Sentio app is still working for you and that you are using the same password.

The error returned from Wavin when logging in is not logged correctly - I will have a look at that.

**Comment by marekbrezina** [comment]
Thanks for your hint djerik. How can I re-enter the password? I have not find the way. Do I need to delete the integration and add as new? Thanks

**Comment by djerik** [comment]
I have added support for reauth, but this required a change in how settings are stores. This again means, that a reauth must store a new set of settings and hence creating another set of entities.

If you update to version 0.3.0, you can try it out. Just remove the old integration that will still fail after reauth. Else remove first and add as new.
